<?php

/**
 * PluginklEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklEventTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklEvent');
    }
}