<?php

/**
 * PluginklEventSubscribersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklEventSubscribersTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklEventSubscribersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklEventSubscribers');
    }
}