<?php

/**
 * PluginklEventSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklEventSubscriberTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklEventSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklEventSubscriber');
    }
}