<?php
/**
 * PluginjFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileTable extends myDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginjFileTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginjFile');
  }

  /**
   * {@inheritDoc}
   */
  public function construct()
  {
    $this->addNamedQuery('get.by.label', $this->createQuery($this->getComponentName())->andWhere('flabel = ?'));
    $this->addNamedQuery('get.by.key', $this->createQuery($this->getComponentName())->andWhere('fkey = ?'));
  }
}