<?php

/**
 * PluginjFileMimeTypeGroupRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileMimeTypeGroupRefTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileMimeTypeGroupRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileMimeTypeGroupRef');
    }
}