<?php

/**
 * PluginjFileMimeTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileMimeTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileMimeTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileMimeType');
    }
}