<?php

/**
 * PluginjFileDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileDocumentTable extends jFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileDocument');
    }
}