<?php

/**
 * PluginjFileAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileAttachmentTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileAttachment');
    }
}