<?php

/**
 * PluginjFileImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileImageTable extends jFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileImage');
    }
}