<?php

/**
 * PluginjFileMimeTypeGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileMimeTypeGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileMimeTypeGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileMimeTypeGroup');
    }
}