<?php

/**
 * PluginjFileExternalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjFileExternalTable extends jFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjFileExternalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjFileExternal');
    }
}