# Фильтры для сохранения выборки параметров.
FxShopFilter:
  actAs:
    FlexibleTree:
      hasManyRoots: true
    Commentable: ~
    Complaintable: ~
    Ignoreable: ~
    Rateable: ~
    Restrictable: ~
    Reviewable: ~
    Watchable: ~
    Sortable: ~
    Taggable: ~
    Sluggable:
      unique: true
      fields: [title]
      builder: [klSluggableBuilder, translit]
      canUpdate: true
    Timestampable: ~
    jFileAttachable: ~
    Watchdogable: ~
  columns:
    id:             { type: integer(5), primary: true, autoincrement: true, unsigned: true }
    label:          { type: string(255), notnull: false }
    title:          { type: clob(16777215), notnull: true }
    annotation:     { type: clob, notnull: false, default: null }
    detail:         { type: clob, notnull: false, default: null }
    note:           { type: clob, notnull: false, default: null }
    is_active:      { type: integer(1), notnull: true, default: 1 }
#    is_params:      { type: integer(1), notnull: true, default: 1 }
    is_category:    { type: integer(1), notnull: true, default: 0 }
#    is_limit:       { type: integer(1), notnull: true, default: 0 }
#    begin_limit:    { type: integer(3), notnull: false, default: null }
#    finish_limit:   { type: integer(3), notnull: false, default: null }
  relations:
    Rules:
      class: FxShopFilterRule
      type: many
      local: id
      foreign: filter_id
      foreignType: one
      foreignAlias: FxShopFilter
      onDelete: RESTRICT
      onUpdate: CASCADE
    Components:
      class: jBehaviorComponent
      local: filter_id
      foreign: component_id
      refClass: FxShopFilterRule
      foreignAlias: FxShopFilters
    Parameters:
      class: jParameterableSchema
      local: filter_id
      foreign: parameter_id
      refClass: FxShopFilterRule
      foreignAlias: FxShopFilters
