# Фильтры для сохранения
# правил фильтрации элементов компонентов.
FxShopFilter:
  actAs:
#    Ignoreable: ~
#    Rateable: ~
#    Watchable: ~
#    Sortable: ~
#    Taggable: ~
    Timestampable: ~
    Watchdogable: ~
  columns:
    id:             { type: integer(5), primary: true, autoincrement: true, unsigned: true }
    label:          { type: string(255), notnull: false }
    title:          { type: clob(16777215), notnull: true }
    annotation:     { type: clob, notnull: false, default: null }
    detail:         { type: clob, notnull: false, default: null }
    note:           { type: clob, notnull: false, default: null }
    is_active:      { type: integer(1), notnull: true, default: 1 }
    is_category:    { type: integer(1), notnull: true, default: 0 }
  relations:
    Rules:
      class: FxShopFilterRule
      type: many
      local: id
      foreign: filter_id
      foreignType: one
      foreignAlias: FxShopFilter
      onDelete: RESTRICT
      onUpdate: CASCADE
    Components:
      class: jBehaviorComponent
      local: filter_id
      foreign: component_id
      refClass: FxShopFilterRule
      foreignAlias: FxShopFilters
    Parameters:
      class: jParameterableSchema
      local: filter_id
      foreign: parameter_id
      refClass: FxShopFilterRule
      foreignAlias: FxShopFilters
