# Перечень (список) чего-либо.
FxShopList:
  actAs:
    FlexibleTree:
      hasManyRoots: true
    Commentable: ~
    Complaintable: ~
    Ignoreable: ~
    Rateable: ~
    Restrictable: ~
    Reviewable: ~
    Watchable: ~
    Sortable: ~
    Taggable: ~
    Sluggable:
      unique: true
      fields: [title]
      builder: [klSluggableBuilder, translit]
      canUpdate: true
    Timestampable: ~
    jFileAttachable: ~
    Watchdogable: ~
  columns:
    id:           { type: integer(5), primary: true, autoincrement: true, unsigned: true }
    ident:        { type: string(255), notnull: false }
    label:        { type: string(255), notnull: false }
    title:        { type: clob(16777215), notnull: true }
    annotation:   { type: clob, notnull: false, default: null }
    detail:       { type: clob, notnull: false, default: null }
    note:         { type: clob, notnull: false, default: null }
    is_active:    { type: integer(1), notnull: true, default: 1 }
    is_category:  { type: integer(1), notnull: true, default: 0 }
