#!/bin/sh

# Definition current execution dir.
EXEC_DIR=$(cd $(dirname "$0"); pwd)

# Definition path to php.
PHP_CMD=`which php`

${PHP_CMD} ${EXEC_DIR}/symfony cc
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:generate-migrations-db
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:drop-db
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:build-db
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:migrate

