#!/bin/sh

# Definition current execution dir.
EXEC_DIR=$(cd $(dirname "$0"); pwd)

# Definition path to php.
PHP_CMD=`which php`

echo "Do you have changes database?"
read -p " Yes / No ?" answer
if [ "${answer}" != "yes" -a "${answer}" != "y" ] ; then
        echo "Bye"
	exit
fi
                
${PHP_CMD} ${EXEC_DIR}/symfony cc
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:generate-migrations-models
