#!/bin/sh

# Definition current execution dir.
EXEC_DIR=$(cd $(dirname "$0"); pwd)

# Definition path to php.
PHP_CMD=`which php`
RM_CMD=`which rm`
GIT_CMD=`which git`

${PHP_CMD} ${EXEC_DIR}/symfony cc

echo "Remove all files from lib and plugins?"
read -p " Yes / No ?" answer
if [ "${answer}" = "yes" -o "${answer}" = "y" ] ; then

	echo "Remove all contains in the /plugins/..."
	${RM_CMD} -rf ${EXEC_DIR}/plugins/*

  echo "Synchronize with repository (HEAD)..."
  ${GIT_CMD} fetch --all
  ${GIT_CMD} --hard origin/master
fi

echo "Cleaning all libraries..."
${RM_CMD} -rf ${EXEC_DIR}/lib/filter
${RM_CMD} -rf ${EXEC_DIR}/lib/form
${RM_CMD} -rf ${EXEC_DIR}/lib/model
${RM_CMD} -rf ${EXEC_DIR}/lib/migration
${RM_CMD} -rf ${EXEC_DIR}/plugins/*/lib/filter
${RM_CMD} -rf ${EXEC_DIR}/plugins/*/lib/form
${RM_CMD} -rf ${EXEC_DIR}/plugins/*/lib/model

echo "Create doctrine classes and sql..."
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:build --all-classes
${PHP_CMD} ${EXEC_DIR}/symfony doctrine:build-sql

echo "Build database?"
read -p " Yes / No ?" answer
if [ "${answer}" = "yes" -o "${answer}" = "y" ] ; then
	${PHP_CMD} ${EXEC_DIR}/symfony doctrine:build --db --no-confirmation
fi

exit 1