<?php

/**
 * PluginjElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjElementTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjElement');
    }
}