<?php

/**
 * PluginklSiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklSiteTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklSiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklSite');
    }
}