prod:
  .settings:
    cache:                  true
    no_script_name:         true
    etag:                   true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL)."\n" ?>
    web_debug:              true
    logging_enabled:        true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    module_disabled_module: default   # To be called when a user requests
    module_disabled_action: disabled  # A module disabled in the module.yml

  .settings:
    compressed:             true
    default_timezone:       "Europe/Moscow"
    # Form security secret (CSRF protection)
    csrf_secret:            false     # Unique secret to enable CSRF protection or false to disable

    # Output escaping settings
    escaping_strategy:      true              # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS  # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Optional features. Deactivating unused features boots performance a bit.
    use_database:           true        # Enable database manager. Set to off if you don't use a database.
    i18n:                   true        # Enable interface translation. Set to off if your application should not be translated.
    check_symfony_version:  false       # Enable check of symfony version for every request. Set to on to have symfony clear the cache automatically when the framework is upgraded. Set to off if you always clear the cache after an upgrade.
    compressed:             false       # Enable PHP response compression. Set to on to compress the outgoing HTML via the PHP handler.
    check_lock:             false       # Enable the application lock system triggered by the clear-cache and disable tasks. Set to on to have all requests to disabled applications redirected to the $sf_symfony_lib_dir/exception/data/unavailable.php page.

    # Routing settings
    relative_url_root:                  # Default URL prefix. Use this when your symfony project is installed in a sub directory of the apache document root.
    no_script_name:         false       # Enable the front controller name in generated URLs

    # Validation settings, used for error generation by the Validation helper
    validation_error_prefix:    ' &darr;&nbsp;'
    validation_error_suffix:    ' &nbsp;&darr;'
    validation_error_class:     form_error
    validation_error_id_prefix: error_for_

    # Cache settings
    cache:                  false       # Enable the template cache
    etag:                   true        # Enable etag handling

    # Logging and debugging settings
    # Enable the web debug toolbar
    web_debug:              false

    # Determines which events are logged.
    error_reporting:        <?php echo (E_PARSE | E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR)."\n" ?> 

    # Activated modules from plugins or from the symfony core
    enabled_modules:
      - default
      - j_fronblock
      - j_options
      - j_softpath
      - j_users
      - jApi
      - jClients
      - jDoctrineFBSuggestJson
      - jExternalPay
      - jKeys
      - jPayments
      - jTest
      - sfGuardAuth
      - sfGuardForgotPassword
      - sfGuardRegister

    # Charset used for the response
    charset:                utf-8

    # Miscellaneous
    strip_comments:         true         # Remove comments in core framework classes as defined in the core_compile.yml
    max_forwards:           5
    path_info_array:        SERVER
    path_info_key:          PATH_INFO
    url_format:             PATH

    # ORM
    orm:                    doctrine

    # Logging
    logging_enabled:        false

    # i18n
    default_culture:        ru        # Default user culture