<?php

/**
 * PluginjRestrictableRecordReasonsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjRestrictableRecordReasonsTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjRestrictableRecordReasonsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjRestrictableRecordReasons');
    }
}