<?php

/**
 * PluginjParameterableDecimalValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableDecimalValueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableDecimalValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableDecimalValue');
    }
}