<?php

/**
 * PluginjParameterableTimeValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableTimeValueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableTimeValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableTimeValue');
    }
}