<?php

/**
 * PluginjCommentableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjCommentableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjCommentableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjCommentableRecord');
    }
}