<?php

/**
 * PluginjTaggableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjTaggableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjTaggableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjTaggableRecord');
    }
}