<?php

/**
 * PluginjIgnoreableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjIgnoreableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjIgnoreableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjIgnoreableRecord');
    }
}