<?php

/**
 * PluginjWatchdogableRevisionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjWatchdogableRevisionsTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjWatchdogableRevisionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjWatchdogableRevisions');
    }
}