<?php

/**
 * PluginjRestrictableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjRestrictableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjRestrictableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjRestrictableRecord');
    }
}