<?php

/**
 * PluginjRestrictableReasonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjRestrictableReasonTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjRestrictableReasonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjRestrictableReason');
    }
}