<?php

/**
 * PluginjParameterableStringValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableStringValueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableStringValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableStringValue');
    }
}