<?php

/**
 * PluginjWatchableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjWatchableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjWatchableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjWatchableRecord');
    }
}