<?php

/**
 * PluginjJoinedRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjJoinedRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjJoinedRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjJoinedRecord');
    }
}