<?php

/**
 * PluginjParameterableOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableOptionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableOption');
    }
}