<?php

/**
 * PluginjParameterableTimestampValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableTimestampValueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableTimestampValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableTimestampValue');
    }
}