<?php
/**
 * PluginjParameterableSchema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginjParameterableSchema extends BasejParameterableSchema
{
  private $currentValue = null;
  private $probablyValues = null;

  public function setCurrentValue($value)
  {
    $this->currentValue = $value;
  }

  public function getCurrentValue()
  {
    return $this->currentValue;
  }

  public function setProbablyValues($a)
  {

  }

  /**
   * Type of the parameter: decimal
   * 
   * @var string
   */
  const DECIMAL_TYPE_NAME = 'decimal';

  /**
   * Length of the parameter: decimal
   * 
   * @var integer
   */
  const DECIMAL_TYPE_LENGTH = 16;

  /**
   * Scale of the parameter: decimal
   * 
   * @var integer
   */
  const DECIMAL_TYPE_SCALE = 3;

  /**
   * Type of the parameter: integer
   * 
   * @var string
   */
  const INTEGER_TYPE_NAME = 'integer';

  /**
   * Length of the parameter: integer
   * 
   * @var integer
   */
  const INTEGER_TYPE_LENGTH = 8;

  /**
   * Type of the parameter: string
   * 
   * @var string
   */
  const STRING_TYPE_NAME = 'string';

  /**
   * Type of the parameter: enum
   * 
   * @var string
   */
  const ENUM_TYPE_NAME = 'enum';

  /**
   * Type of the parameter: date
   * 
   * @var string
   */
  const DATE_TYPE_NAME = 'date';

  /**
   * Type of the parameter: time
   * 
   * @var string
   */
  const TIME_TYPE_NAME = 'time';

  /**
   * Type of the parameter: checkbox
   * 
   * @var string
   */
  const CHECKBOX_TYPE_NAME = 'checkbox';

  /**
   * Type of the parameter: radio
   * 
   * @var string
   */
  const RADIO_TYPE_NAME = 'radio';

  /**
   * Type of the parameter: timestamp
   * 
   * @var string
   */
  const TIMESTAMP_TYPE_NAME = 'timestamp';

  /**
   * Type of the parameter: liblink
   * 
   * @var string
   */
  const LIBLINK_TYPE_NAME = 'liblink';

  /**
   * Type of the parameter: image
   * 
   * @var string
   */
  const IMAGE_TYPE_NAME = 'image';

  /**
   * Type of the parameter: document
   * 
   * @var string
   */
  const DOCUMENT_TYPE_NAME = 'document';

  /**
   * Type of the parameter: file
   * 
   * @var string
   */
  const FILE_TYPE_NAME = 'file';

  /**
   * Type of the parameter: address
   * 
   * @var string
   */
  const ADDRESS_TYPE_NAME = 'address';
}