<?php

/**
 * PluginjParameterableIntegerValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableIntegerValueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableIntegerValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableIntegerValue');
    }
}