<?php

/**
 * PluginjScheduledTemplateRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjScheduledTemplateRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjScheduledTemplateRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjScheduledTemplateRecord');
    }
}