<?php

/**
 * PluginjParameterableSchemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableSchemaTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableSchemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableSchema');
    }
}