<?php

/**
 * PluginjBehaviorComponentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjBehaviorComponentTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjBehaviorComponentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjBehaviorComponent');
    }
}