<?php

/**
 * PluginjTaggableTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjTaggableTagTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjTaggableTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjTaggableTag');
    }
}