<?php

/**
 * PluginjScheduleableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjScheduleableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjScheduleableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjScheduleableRecord');
    }
}