<?php

/**
 * PluginjParameterableDateValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjParameterableDateValueTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjParameterableDateValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjParameterableDateValue');
    }
}