<?php

/**
 * PluginjSignableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjSignableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjSignableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjSignableRecord');
    }
}