<?php

/**
 * PluginjRateableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjRateableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjRateableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjRateableRecord');
    }
}