<?php

/**
 * PluginjReviewableRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginjReviewableRecordTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginjReviewableRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginjReviewableRecord');
    }
}