all:
  # jDoctrineProfilePlugin.
  #----------------------------------------------------------------------------
  yaMorphyPlugin:
    enable: true
    instances:
      ru_ru:
        utf-8:
          dictionary_directory: dicts
          options:
            storage: file
            predict_by_suffix: true
            predict_by_db: true
            graminfo_as_text: true
          shm:
            segment_size: 32
            semaphore_key: 1024
            segment_id: 1024    
      en_en:
        cp1250:
          dictionary_directory: dicts
          options:
            storage: file
            predict_by_suffix: true
            predict_by_db: true
            graminfo_as_text: true
          shm:
            segment_size: 32
            semaphore_key: 1024
            segment_id: 1024  

