<?php

/**
 * PluginklLayoutStyleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklLayoutStyleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklLayoutStyleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklLayoutStyle');
    }
}