<?php

/**
 * PluginklLayoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklLayoutTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklLayoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklLayout');
    }
}