<?php

/**
 * PluginklLayoutScriptsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklLayoutScriptsTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklLayoutScriptsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklLayoutScripts');
    }
}