<?php

/**
 * PluginklLayoutScriptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklLayoutScriptTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklLayoutScriptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklLayoutScript');
    }
}