<?php

/**
 * PluginklLayoutStylesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklLayoutStylesTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklLayoutStylesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklLayoutStyles');
    }
}