all:
  storage:
    class: sfSessionStorage
    param:
      auto_start:               true
      session_name:             klsid
      session_cookie_lifetime:  31556926
      session_cache_limiter:    private_no_expire

  i18n:
    class: sfI18N
    param:
      source:               XLIFF
      debug:                false
      untranslated_prefix:  "[T]"
      untranslated_suffix:  "[/T]"
      cache:
        class: sfFileCache
        param:
          automatic_cleaning_factor: 0
          cache_dir:                 %SF_I18N_CACHE_DIR%
          lifetime:                  7889231
          prefix:                    %SF_APP_DIR%/i18n

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  view_cache:
    class: sfFileCache
    param:
      automatic_cleaning_factor:  0
      cache_dir:                  %SF_TEMPLATE_CACHE_DIR%
