all:
  .settings:
    default_culture:        "ru"
    default_timezone:       "Europe/Moscow"
    standard_helpers:
      - Asset
      - Partial
      - Cache
      - I18N
      - Escaping
      - Tag
      - JavascriptBase
      - Url
      - jDatetime
      - jString
      - yaJavascript
      - yaUrl

prod:
  .settings:
    no_script_name:         true
    etag:                   true
    cache:                  true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL)."\n" ?>
    web_debug:              true

test:
  .settings:
    error_reporting:        <?php echo (E_ALL)."\n" ?>
