default:
  http_metas:
    content-type: text/html
    charset: utf-8
    X-UA-Compatible: IE=Edge,chrome=1

  metas:
    language:     ru
    robots:       all
    viewport:     "width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0"

  has_layout:     true
  layout:         _layout/default
