<?php

/**
 * PluginklUserPasswordKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserPasswordKeyTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserPasswordKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserPasswordKey');
    }
}