<?php

/**
 * PluginklUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserPermissionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserPermission');
    }
}