<?php

/**
 * PluginklUserActivateKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserActivateKeyTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserActivateKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserActivateKey');
    }
}