<?php

/**
 * PluginklUserTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserTokenTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserToken');
    }
}