<?php

/**
 * PluginklUserRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserRememberKeyTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserRememberKey');
    }
}