<?php

/**
 * PluginklUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserGroup');
    }
}