<?php

/**
 * PluginklUserGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserGroupPermissionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserGroupPermission');
    }
}