<?php

/**
 * PluginklUserUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklUserUserGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklUserUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklUserUserGroup');
    }
}