<?php

/**
 * PluginklPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginklPermissionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginklPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginklPermission');
    }
}