<?php

/**
 * PluginWordTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWordTemplateTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWordTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWordTemplate');
    }
}