<?php

/**
 * PluginFxShopFilterGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopFilterGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopFilterGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopFilterGroup');
    }
}