<?php

/**
 * PluginFxShopFilterOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopFilterOrderTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopFilterOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopFilterOrder');
    }
}