<?php

/**
 * PluginFxShopListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopListTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopList');
    }
}