<?php

/**
 * PluginFxShopFilterHavingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopFilterHavingTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopFilterHavingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopFilterHaving');
    }
}