<?php

/**
 * PluginItemsWordsRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginItemsWordsRefTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginItemsWordsRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginItemsWordsRef');
    }
}