<?php

/**
 * PluginFxShopFilterRuleGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopFilterRuleGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopFilterRuleGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopFilterRuleGroup');
    }
}