<?php

/**
 * PluginFxShopFilterRuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopFilterRuleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopFilterRuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopFilterRule');
    }
}