<?php

/**
 * PluginFxShopItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFxShopItemTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFxShopItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFxShopItem');
    }
}